### ISSUE TITLE
`gulp` stops for `tsc -p src`

### ISSUE THREAD

**Issue by Yaojian** [Justin-Credible/Ionic-TypeScript-Starter#12]
The error:

````
[19:07:23] Starting 'ts'...
error TS5023: Unknown option 'p'
Use the '--help' flag to see options.

error TS5007: Cannot resolve referenced file: 'src'.


[19:07:24] 'ts' errored after 1.33 s
[19:07:24] Error: Command failed: C:\Windows\system32\cmd.exe /s /c "tsc -p src"
error TS5007: Cannot resolve referenced file: 'src'.


    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
[19:07:24] 'default' errored after 53 s
[19:07:24] Error: [object Object]
    at formatError (C:\Users\Yaojian\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\Yaojian\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (C:\Yaojian\Projects\TsIonic\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at C:\Yaojian\Projects\TsIonic\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (C:\Yaojian\Projects\TsIonic\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\Yaojian\Projects\TsIonic\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (C:\Yaojian\Projects\TsIonic\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (C:\Yaojian\Projects\TsIonic\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:129:20)
````

I tried `tsc --p src` at command line and got the same error.

**Comment by Yaojian** [comment]
The typescript compiler is outdated. The `tsc` in my `PATH` refers to an old version at `C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\`.
