### ISSUE TITLE
Update to support latest versions of npm modules (eg TypeScript 1.5.3, Ionic CLI 1.6.x etc)

### ISSUE THREAD

**Issue by tjaffri** [Justin-Credible/Ionic-TypeScript-Starter#24]
Hey. I'm just getting started with Ionic and TypeScript so apologies in advance if there is something simple I'm missing here.

First I made sure I had the pre-reqs installed that you list under environment setup. I installed the latest versions, though, and installed them globally for now to keep things simple. Here's my "npm list -g -depth 0":

grposey-s3:Documents tjaffri$ npm list -g -depth 0
/usr/local/lib
├── appbuilder@2.11.1
├── **bower@1.4.1**
├── **bower-installer@1.2.0**
├── **cordova@5.1.1**
├── gulp@3.9.0
├── **ionic@1.6.4**
├── **node.js@0.0.0**
├── npm@2.13.4
├── plugman@0.23.3
├── **tsc@1.20150623.0**
├── **tsd@0.6.3**
├── **typescript@1.5.3**
└── yo@1.4.7

Next, I cloned your repo and installed the node packages it needs: 
```
$ git clone https://github.com/Justin-Credible/Ionic-TypeScript-Starter.git
$ cd Ionic-TypeScript-Starter
$ npm install
```

All seems well at this point, but when I run "gulp" or "ionic serve" I get the following error spew.

```
[10:57:32] Finished 'tsd:tests' after 1.55 s
[10:57:32] Finished 'tsd' after 4.76 s
[10:57:32] Starting 'ts:vars'...
[10:57:32] Finished 'ts:vars' after 23 ms
[10:57:32] Starting 'ts:src-read-me'...
[10:57:32] Finished 'ts:src-read-me' after 7.96 ms
[10:57:32] Starting 'ts:src'...
[10:57:32] Finished 'ts:src' after 64 ms
[10:57:32] Starting 'ts'...
src/Application.ts(44,26): error TS2503: Cannot find namespace 'Interfaces'.
src/Application.ts(55,34): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(56,34): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(57,34): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(58,35): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(58,73): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(58,111): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(59,36): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(67,73): error TS2339: Property 'ripple' does not exist on type 'Window'.
src/Application.ts(69,47): error TS2339: Property 'buildVars' does not exist on type 'Window'.
src/Application.ts(327,31): error TS2305: Module 'Ionic' has no exported member 'IPlatform'.
src/Controllers/BaseController.ts(56,75): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(69,74): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(82,74): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(95,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(108,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(121,79): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(134,79): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/BaseController.ts(147,77): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/CategoryController.ts(30,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Onboarding/OnboardingRegisterController.ts(34,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/RootController.ts(36,75): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/AboutController.ts(26,34): error TS2503: Cannot find namespace 'Interfaces'.
src/Controllers/Settings/AboutController.ts(34,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/CloudSyncController.ts(31,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/CloudSyncController.ts(41,74): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/ConfigurePinController.ts(28,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/DeveloperController.ts(40,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/LogEntryController.ts(29,34): error TS2503: Cannot find namespace 'Interfaces'.
src/Controllers/Settings/LogEntryController.ts(39,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/LogEntryController.ts(74,41): error TS2339: Property 'printStackTrace' does not exist on type 'Window'.
src/Controllers/Settings/LogsController.ts(30,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Controllers/Settings/SettingsListController.ts(28,80): error TS2305: Module 'Ionic' has no exported member 'IViewEventArguments'.
src/Services/Configuration.ts(22,32): error TS2304: Cannot find name 'BuildVars'.
src/Services/FileUtilities.ts(124,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(129,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(216,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(221,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(293,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(298,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(397,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(402,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(471,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(476,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(545,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(550,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(649,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(654,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(721,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(726,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1011,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1016,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1181,35): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1186,24): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1300,35): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1305,24): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1401,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1406,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1462,31): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/FileUtilities.ts(1467,20): error TS2339: Property 'resolveLocalFileSystemURL' does not exist on type 'Window'.
src/Services/HttpInterceptor.ts(99,32): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(99,59): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(174,25): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(177,23): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(204,25): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(221,27): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(241,25): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(254,27): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(297,44): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/HttpInterceptor.ts(365,43): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/Logger.ts(270,45): error TS2503: Cannot find namespace 'Interfaces'.
src/Services/MockPlatformApis.ts(34,34): error TS2304: Cannot find name 'ICordovaToastPlugin'.
src/Services/MockPlatformApis.ts(54,38): error TS2304: Cannot find name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(61,56): error TS2304: Cannot find name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(80,46): error TS2304: Cannot find name 'ICordovaProgressIndicator'.
src/Services/MockPlatformApis.ts(121,40): error TS2304: Cannot find name 'ICordovaCrashlyticsPlugin'.
src/Services/UiHelper.ts(62,22): error TS2304: Cannot find name 'ICordovaToastPlugin'.
src/Services/UiHelper.ts(63,78): error TS2339: Property 'toast' does not exist on type 'Plugins'.
src/Services/UiHelper.ts(64,39): error TS2339: Property 'toast' does not exist on type 'Plugins'.
src/Services/UiHelper.ts(74,34): error TS2304: Cannot find name 'ICordovaProgressIndicator'.
src/Services/UiHelper.ts(75,52): error TS2339: Property 'ProgressIndicator' does not exist on type 'Window'.
src/Services/UiHelper.ts(76,31): error TS2339: Property 'ProgressIndicator' does not exist on type 'Window'.
src/Services/UiHelper.ts(86,26): error TS2304: Cannot find name 'ICordovaClipboardPlugin'.
src/Services/UiHelper.ts(87,115): error TS2339: Property 'clipboard' does not exist on type 'CordovaPlugins'.
src/Services/UiHelper.ts(88,40): error TS2339: Property 'clipboard' does not exist on type 'CordovaPlugins'.
src/Services/UiHelper.ts(125,28): error TS2304: Cannot find name 'ICordovaCrashlyticsPlugin'.
src/Services/UiHelper.ts(126,92): error TS2339: Property 'crashlytics' does not exist on type 'Navigator'.
src/Services/UiHelper.ts(127,34): error TS2339: Property 'crashlytics' does not exist on type 'Navigator'.
src/Services/Utilities.ts(25,32): error TS2304: Cannot find name 'BuildVars'.
src/Services/Utilities.ts(105,38): error TS2339: Property 'ripple' does not exist on type 'Window'.
src/Controllers/Settings/AboutController.ts(26,34): error TS4063: Parameter 'versionInfo' of constructor from exported class has or is using private name 'Interfaces'.
src/Controllers/Settings/LogEntryController.ts(29,34): error TS4063: Parameter 'versionInfo' of constructor from exported class has or is using private name 'Interfaces'.
src/Services/Configuration.ts(22,32): error TS4063: Parameter 'buildVars' of constructor from exported class has or is using private name 'BuildVars'.
src/Services/HttpInterceptor.ts(99,32): error TS4073: Parameter 'config' of public method from exported class has or is using private name 'Interfaces'.
src/Services/HttpInterceptor.ts(99,59): error TS4055: Return type of public method from exported class has or is using private name 'Interfaces'.
src/Services/Logger.ts(270,45): error TS4073: Parameter 'config' of public method from exported class has or is using private name 'Interfaces'.
src/Services/MockPlatformApis.ts(34,34): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaToastPlugin'.
src/Services/MockPlatformApis.ts(54,38): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(61,56): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaClipboardPlugin'.
src/Services/MockPlatformApis.ts(80,46): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaProgressIndicator'.
src/Services/MockPlatformApis.ts(121,40): error TS4055: Return type of public method from exported class has or is using private name 'ICordovaCrashlyticsPlugin'.
src/Services/UiHelper.ts(62,22): error TS4043: Return type of public property getter from exported class has or is using private name 'ICordovaToastPlugin'.
src/Services/UiHelper.ts(74,34): error TS4043: Return type of public property getter from exported class has or is using private name 'ICordovaProgressIndicator'.
src/Services/UiHelper.ts(86,26): error TS4043: Return type of public property getter from exported class has or is using private name 'ICordovaClipboardPlugin'.
src/Services/UiHelper.ts(125,28): error TS4043: Return type of public property getter from exported class has or is using private name 'ICordovaCrashlyticsPlugin'.
src/Services/Utilities.ts(25,32): error TS4063: Parameter 'buildVars' of constructor from exported class has or is using private name 'BuildVars'.


[10:57:35] 'ts' errored after 2.69 s
[10:57:35] Error: Command failed: /bin/sh -c tsc -p src

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
[10:57:35] 'default' errored after 26 s
[10:57:35] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/tjaffri/Documents/Ionic-TypeScript-Starter/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/tjaffri/Documents/Ionic-TypeScript-Starter/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/tjaffri/Documents/Ionic-TypeScript-Starter/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/tjaffri/Documents/Ionic-TypeScript-Starter/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/tjaffri/Documents/Ionic-TypeScript-Starter/node_modules/run-sequence/index.js:53:5)
    at Gulp.onError (/Users/tjaffri/Documents/Ionic-TypeScript-Starter/node_modules/run-sequence/index.js:60:4)
    at Gulp.emit (events.js:129:20)
```

Any help is much appreciated. Thanks!

**Comment by Justin-Credible** [comment]
I would recommend using the same versions as listed in `package.json` without installing them globally. This is easy to do if you put `./node_modules/.bin` in your path and then follow the rest of the steps in the `readme.md`.

I've found that there are so many libraries and moving parts, it just makes things much easier to use the specific known-good configuration.

After you've got the project running in this matter, you can upgrade individual packages (eg TypeScript 1.5.3) one at a time.

**Comment by tjaffri** [comment]
Thanks, I tried that earlier but didn't have much luck. Turns out the versions listed in README.md are not in sync with package.json so I was installing the wrong versions.

I could fork and issue a pull request, but maybe it is faster if you just want to copy-paste the updated versions from below.

```
* Node.js (0.10.28)
* Cordova (5.1.1)
* Ionic (1.5.5)
* TypeScript (1.5.0-beta)
* Bower (1.4.1)
* bower-installer (1.2.0)
* tsd (0.6.1)
```

I would appreciate if you could update the packages and make the build work with latest versions, so keeping this issue open to track that work.

Thank you so much for starting this! Pretty impressive starter with all the utilities, logging, etc... not to mention the TypeScript.

**Comment by Justin-Credible** [comment]
Thanks and sorry for the confusion.

The npm ecosystem changes so quickly that it is hard to keep up with all the new versions. I do need to catch up soon though.

I've updated the title to reflect the purpose of this issue.
