### ISSUE TITLE
Gulp init failed on plugins

### ISSUE THREAD

**Issue by Jerome2606** [Justin-Credible/Ionic-TypeScript-Starter#53]
Hello,

I just made a git clone, type npm install and all were ok
type gulp init and I have this error on plugins task:

    [15:43:52] 'plugins' errored after 39 s
    [15:43:52] Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "cordova plugin add com.verso.cordova.clipboard@0.1.0"
    Error: Failed to fetch plugin com.verso.cordova.clipboard@0.1.0 via registry.
    Probably this is either a connection problem, or plugin spec is incorrect.
    Check your connection and plugin name/version/URL.
    Error: Registry returned 404 for GET on https://registry.npmjs.org/com.verso.cordova.clipboard

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    [15:43:52] Finished 'init' after 56 s
    [15:43:52] 'default' errored after 39 s
    [15:43:52] Error in plugin 'run-sequence'
    Message:
    An error occured in task 'plugins'.

Any idea about this plugin 404 error?

**Comment by Jerome2606** [comment]
Oups, after reading the readme with more attention:

> ensure that you've added ./node_modules/bin to your path

I set the path with the specified value and .. ALL IS OK :) !!
