### ISSUE TITLE
problem in gulp init

### ISSUE THREAD

**Issue by elmor34** [Justin-Credible/Ionic-TypeScript-Starter#58]
I get the following message and app do not start.
node version is 5.6.0
npm install done.
regards
Gokhan
....
Fetching plugin "cordova-plugin-x-toast@2.2.1" via npm
Installing "cordova-plugin-x-toast" for android
Installing "cordova-plugin-x-toast" for ios

Fetching plugin "cordova-universal-clipboard@0.1.0" via npm
Installing "cordova-universal-clipboard" for android
Installing "cordova-universal-clipboard" for ios

[07:47:25] Finished 'plugins' after 48 s
[07:47:25] Starting 'libs'...

/bin/sh: bower-installer: command not found

[07:47:25] 'libs' errored after 9.19 ms
[07:47:25] Error: Command failed: /bin/sh -c bower-installer
/bin/sh: bower-installer: command not found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[07:47:25] Finished 'init' after 1.12 min
[07:47:25] 'default' errored after 48 s
[07:47:25] Error in plugin 'run-sequence'
Message:
    An error occured in task 'libs'.

....

**Comment by Justin-Credible** [comment]
Please ensure you can run `bower-installer --help` from the directory where you cloned the starter project.

If you don't get the bower installer help message then please double check that you've added `./node_modules/.bin` as per the readme.
